version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=$P{DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}