version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: database_container
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
     #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}